version: '3'

services:
  loei-a6-express:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: loei-a6-express
    restart: unless-stopped
    ports:
      - '5000:5000'
    links:
      - mongodb
    volumes:
      - .:/app
    command: nodemon --watch . --exec "node" index.js

networks:
  default:
    external:
      name: default-net
